### ISSUE TITLE
what is "UnstyledLink" ?

### ISSUE THREAD

**Issue by AbhishekCode** [oliverfencott/material-tabs#1]
Your package looks good. but i have a issue implementing it.
you have used `UnstyledLink` in example. Can you explain what component is that and do we need it? I tried replacing that with div but didn't worked. Thanks.

**Comment by oliverfencott** [comment]
Hi, thanks for reporting an issue.

Can I ask what's not working? What error are you getting?

To answer your question, `UnstyledLink` is just a custom component I was using in the example, which is an instance of the `Link` component provided by React-Router, with no default styling applied.

**Comment by AbhishekCode** [comment]
I am not sure about 'unstyledLink' you used in example.  Is it a component
you made and not included in project or its external dependency ?
On 20-Apr-2016 7:33 pm, "Oliver Fencott" notifications@github.com wrote:

Hi, thanks for reporting an issue.

Can I ask what's not working? What error are you getting?

**Comment by oliverfencott** [comment]
Yes, it's just a custom component specific to that project. If you're using `react-router`, you can just use `Link` instead and it's functionally equivalent.

**Comment by AbhishekCode** [comment]
Okay. Thanks
