### ISSUE TITLE
Error with Webpack

### ISSUE THREAD

**Issue by aleksandar-b** [oliverfencott/material-tabs#2]
Getting error 
`bundle.js:1 Warning: TabGroup(...): React component classes must extend React.Component.

`Uncaught Invariant Violation: TabGroup.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.`
I think that has something to do with Webpack...

see:
-https://github.com/tleunen/react-number-editor/issues/17

![image](https://cloud.githubusercontent.com/assets/13149550/16712465/c06496d8-4688-11e6-9265-e48c5b97ef62.png)

**Comment by aleksandar-b** [comment]
I was able to solve this by moving react from dependencies to devDependencies.

**Comment by mx-scissortail** [comment]
I'm getting the same error with Browserify. If I do this: 

``` javascript
import {TabGroup, Tab} from 'material-tabs';
console.log(TabGroup);
```

I see "undefined", so something is wrong with the way things are being exported?

**Comment by oliverfencott** [comment]
@j-s-n :

You are correct. The issue wasn't to do the way the files were being exported, but the way they were imported, i.e.

``` js
import materialTabs from 'material-tabs';

const { TabGroup, Tab } = materialTabs;
```

would have worked.

I have added `TabGroup` and `Tab` as named exports, as well as on the default export so you can use either syntax now and should be free from error.
